### ISSUE TITLE
Clarify direct vs indirect proxiers on profile page

### ISSUE THREAD

**Issue by dsernst** [unitedvote/united.vote#22]
> Dallas Cole [2 days ago]
> couple thoughts on the profile page: right now it shows I represent 46 people; think it would help to break that down by who I represent directly vs indirectly

> David Ernst [2 days ago]
> E.g. "Represents 3 people directly, and 46 people indirectly"?

> Sergey Pankov [2 days ago]
> If so, then A directly, B at degree of separation 1, C at DoS 2, ...

> Dallas Cole [1 hour ago]
> or, leave it as it is now and then provide a breakdown underneath. I'm fine with either directly/indirectly or showing all degrees of seperation, but more info is probably better

**Comment by dsernst** [comment]
Yeah, a “More Info” link that clarifies this could be valuable. Right now we’re not exposing any information about depth of proxying, and we probably just want to be consistent.

**Comment by dsernst** [comment]
Another related question about this (from @doodlemania2)

<img width="1009" alt="screen shot 2018-04-12 at 2 55 58 pm" src="https://user-images.githubusercontent.com/6340841/38706359-b3597922-3e61-11e8-87e3-038315d6f251.png">

**Comment by alexmingoia** [comment]
We've deployed a change to user profiles, so that they state "Represents X people directly, and X people indirectly."
