### ISSUE TITLE
Search bills by author

### ISSUE THREAD

**Issue by dsernst** [unitedvote/united.vote#30]
A number of users have reported being surprised they couldn't do this.

**Comment by dsernst** [comment]
One report a user wrote up after trying to find a bill they read about in the news:

<img width="1396" alt="screen shot 2018-04-16 at 12 15 37 am" src="https://user-images.githubusercontent.com/6340841/38794883-628f70bc-410b-11e8-88db-5450829254c7.png">

**Comment by alexmingoia** [comment]
The sponsor first and last name has been added to the search index, so this works now.

https://united.vote/legislation?order=upcoming&terms=Angus+King shows all of Angus Kind's legislation now.
