### ISSUE TITLE
Legislation list filters

### ISSUE THREAD

**Issue by dsernst** [unitedvote/united.vote#31]
User feedback:

> After I vote on something, remove it from my view, end up scrolling too much!

and

> If there is no text and no summary yet, just don't show it :)

**Comment by dsernst** [comment]
Both of these would work as good filters to add to the legislation list. Simple checkbox:

> - [ ] Hide already voted upon
> - [ ] Hide missing summaries *[blocked by #19]*

**Comment by doodlemania2** [comment]
Suggest additional filter:

- [ ] Has Bill Text

Indicates (just like summaries indicator) if there is text of bill present or not.

Then, make the above filters, not just visual representations...icons are great, but to move through legislation fast, I need to have good filters, like what was just added for "Hide Direct Votes"

**Comment by doodlemania2** [comment]
Example of a bill with no summary and no text either: https://www.congress.gov/bill/115th-congress/house-bill/5580/text

**Comment by dsernst** [comment]
Ah, yes. Thank you.

![img_2454](https://user-images.githubusercontent.com/6340841/39292836-2f360116-48ec-11e8-8e3b-63c4d0d1fd07.PNG)

Thanks for clarifying.
