### ISSUE TITLE
On Vote, Return to /Legislation

### ISSUE THREAD

**Issue by doodlemania2** [unitedvote/united.vote#38]
Save a click! When I vote, return me to the /legislation page, not the bill page.

**Comment by dsernst** [comment]
Oh good point.

Current thinking is to create and send you to a dedicated page *just* for your vote, with it's own URL (see https://github.com/unitedvote/united.vote/issues/5).

That way you can share it with others, where they can easily proxy to you or upvote your comment.

We can make sure to keep the breadcrumbs at the top for an easy link back to the legislation list.

<img width="260" alt="screen shot 2018-04-23 at 9 44 23 pm" src="https://user-images.githubusercontent.com/6340841/39166681-d6a43e6c-473f-11e8-8cd8-6989af778cf7.png">

What do you think?

**Comment by doodlemania2** [comment]
Love it!
