### ISSUE TITLE
Allow personalized description on profiles

### ISSUE THREAD

**Issue by dsernst** [unitedvote/united.vote#39]
Right now our profile pages are pretty plain. 

Allowing people to add a custom intro / description (with optional video?) could go a long way to helping them want to promote it more.

### Patreon does a pretty good job with this.

For example: https://www.patreon.com/Kurzgesagt

![screen shot 2018-04-24 at 1 49 38 am](https://user-images.githubusercontent.com/6340841/39176492-ce426196-4761-11e8-942b-2fc2a8fe1f8e.png)

**Comment by alexmingoia** [comment]
An "Edit Profile" page has been added and deployed, which allows users to set an intro video and text that appears on their profile.
