### ISSUE TITLE
Allow calls to legislators

### ISSUE THREAD

**Issue by dallasjc** [unitedvote/united.vote#58]
When people select comment on a bill, they should also have an option to call their legislators

United would:

- Require them to read and agree to a code of conduct before using United to place calls
        - No abuse/harassment
- Introduce the call to the Congressional staff
        - “This is a call from a verified voter placed through United.Vote. An email summary will be sent to your office following the call.”
- Record the call and allow people to add it as a public comment
- Send an email to the member of Congress’ office with information, including the person’s name, the bill they were calling about, a link to the recording and a method for reporting abuse by callers
- Review any reported allegations of abuse and suspend people’s ability to use our platform to make calls if necessary 
- we’ll decide this initially, later we’d ask the community to develop a process to help handle these
- Prevent more than two calls in five minutes to the same office, more than 5 in 15 minutes, etc
      - This is meant to prevent people from using our site to “shut down” a congressional office
- Offer the option to record a voicemail and send it to the office later

We could even expand on this later by allowing people to do video chats with an office through our website
 
Should we offer an anonymous option? That way people can call in, don’t have to leave their name and the rep still knows that they’re a constituent

**Comment by dsernst** [comment]
This is a very large undertaking technically, and way out of scope for now, I'm going to close for now and we can revisit later.
