### ISSUE TITLE
United pulled opening summary instead of title

### ISSUE THREAD

**Issue by dallasjc** [unitedvote/united.vote#66]
https://united.vote/legislation/us115-hr6249 the title for this on govtrack is REFUSE Act, but it's super long on united

To amend the Federal Election Campaign Act of 1971 to treat certain foreign-owned corporations and business organizations as foreign nationals for purposes of the ban on campaign activity, to prohibit foreign-affiliated section 501(c)(4) organizations from making contributions to super PACs or disbursing funds for independent expenditures or electioneering communications, to amend the Foreign Agents Registration Act of 1938 to reform the procedures for the registration of agents of foreign principals under such Act, and for other purposes.

**Comment by alexmingoia** [comment]
I see the title as "REFUSE Act" on United.

**Comment by dallasjc** [comment]
strange, me too. maybe united updated it?
